name: branch

on:
  push:
    branches-ignore: [ master, develop, release ]

env:
#  APP_SIGN_KEYSTORE_PATH: /tmp/keystore
  CACHE_BUNDLER: ~/.bundler

jobs:
  build:
    runs-on: windows-latest
    steps:
#      - name: Write key file
#        env:
#          AUTH: ${{ secrets.KEYSTORE }}
#        run: echo $AUTH | base64 --decode > /tmp/keystore

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Bundler cache
        uses: actions/cache@v1
        with:
          path: $CACHE_BUNDLER
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: fastlane android test
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: branch
          options: '{ "conf": "debug" }'
          skip-tracking: false
          subdirectory: fastlane
          bundle-install-path: CACHE_BUNDLER